# Generated by Django 6.1 on 2026-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('studio', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('meta', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='Installed', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_label', models.CharField(blank=True, max_length=50)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(default='Add to Cart', max_length=50)),
                ('added_date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
