# Generated by Django 6.1 on 2026-08-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_communitycomment_userbookmark_userlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('avatar_url', models.URLField(blank=True)),
                ('role', models.CharField(choices=[('gamer', 'Gamer'), ('developer', 'Developer')], default='gamer', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.CharField(blank=True, help_text="e.g. '2m ago'", max_length=40)),
                ('level', models.IntegerField(default=1)),
                ('games_played', models.IntegerField(default=0)),
                ('achievements', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('member_since', models.CharField(blank=True, max_length=40)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-is_online', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserFollowedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='dashboard.communitygame')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_name', 'game')},
            },
        ),
    ]
