# Generated by Django 6.1 on 2026-08-18 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_userwishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='games', max_length=30)),
                ('type', models.CharField(blank=True, help_text='e.g. Action RPG, Metroidvania', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Studio / publisher name', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.URLField(blank=True, help_text='Banner / capsule image URL')),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube trailer URL')),
                ('stock', models.CharField(blank=True, default='In Stock', max_length=100)),
                ('badges', models.CharField(blank=True, help_text='Comma-separated badges', max_length=200)),
                ('developer_name', models.CharField(blank=True, help_text='Developer credit shown on product', max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('release_date', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Admin feedback note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
