# Generated by Django 6.1 on 2026-08-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_gamesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, help_text='List of screenshot image URLs'),
        ),
    ]
