# Generated by Django 6.1 on 2026-08-19 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_screenshots_to_gamesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('author_avatar', models.URLField(blank=True)),
                ('positive', models.BooleanField(default=True)),
                ('text', models.TextField(max_length=2000)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('hours', models.FloatField(blank=True, help_text='Play hours (games only)', null=True)),
                ('helpful', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.shopproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
