# Generated by Django 6.1 on 2026-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('silver', 'Silver'), ('paper', 'Paper'), ('obsidian', 'Obsidian')], default='midnight', max_length=20),
        ),
    ]
