# Generated by Django 6.1 on 2026-08-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('midnight', 'Midnight'), ('silver', 'Silver'), ('paper', 'Paper'), ('obsidian', 'Obsidian')], default='silver', max_length=20),
        ),
    ]
