# Generated by Django 6.1 on 2026-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reduce_animations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sidebar_expanded',
            field=models.BooleanField(default=False),
        ),
    ]
