# Generated by Django 6.1 on 2026-08-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_instagram_user_twitch_user_twitter_user_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_position',
            field=models.IntegerField(default=50),
        ),
    ]
