# Generated by Django 6.1 on 2026-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_banner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('JPY', 'JPY (¥)'), ('IDR', 'IDR (Rp)')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English (US)'), ('ja', 'Japanese'), ('id', 'Indonesian')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('Asia/Jakarta', 'Asia/Jakarta (WIB)'), ('Asia/Tokyo', 'Asia/Tokyo (JST)'), ('Asia/Singapore', 'Asia/Singapore (SGT)'), ('America/New_York', 'New York (EST)'), ('Europe/London', 'London (GMT)'), ('UTC', 'UTC')], default='Asia/Jakarta', max_length=40),
        ),
    ]
